[package]
name = "ecdsa"
version = "5.0.1"
description = "Library to sign and verify with ECDSA"
repository = "https://github.com/edjCase/motoko_ecdsa"
keywords = ["ecdsa", "signature", "verify", "key", "public", "private", "curve"]
license = "Apache-2.0"

[dependencies]
sha2 = "0.1.0"
asn1 = "2.0.2"
xtended-numbers = "0.4.0"
base-x-encoder = "0.0.1"

[dev-dependencies]
test = "2.1.1"
