[package]
name = "ecdsa"
version = "6.0.0"
description = "Library to sign and verify with ECDSA"
repository = "https://github.com/edjCase/motoko_ecdsa"
keywords = ["ecdsa", "signature", "verify", "key", "public", "private", "curve"]
license = "Apache-2.0"

[dependencies]
sha2 = "0.1.4"
asn1 = "2.0.2"
xtended-numbers = "0.4.0"
base-x-encoder = "1.1.0"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.10"
