[package]
name = "ecdsa"
version = "7.0.2"
description = "Library to sign and verify with ECDSA"
repository = "https://github.com/edjCase/motoko_ecdsa"
keywords = [
  "ecdsa",
  "signature",
  "verify",
  "key",
  "public",
  "private",
  "curve",
  "cryptography"
]
license = "Apache-2.0"

[dependencies]
sha2 = "0.1.6"
asn1 = "3.0.1"
xtended-numbers = "2.0.0"
base-x-encoder = "2.0.0"
core = "0.6.0"
buffer = "0.0.1"
xtended-iter = "1.0.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"

[toolchain]
moc = "0.14.14"
