[package]
name = "ecdsa"
version = "7.1.0"
description = "Library to sign and verify with ECDSA"
repository = "https://github.com/edjCase/motoko_ecdsa"
keywords = [
  "ecdsa",
  "signature",
  "verify",
  "key",
  "public",
  "private",
  "curve",
  "cryptography",
]
license = "Apache-2.0"

[dependencies]
"sha2@0" = "0.1.6"
"asn1@3" = "3.1.0"
"xtended-numbers@2" = "2.1.0"
"base-x-encoder@2" = "2.1.0"
"core@1" = "1.0.0"
"buffer@0" = "0.1.0"
"xtended-iter@1" = "1.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
